---
- hosts: web
  become: true
  become_user: root
  tasks:
  - name: Installs nginx web server
    apt: pkg=nginx state=installed update-cache=true
    notify:
    - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started

