---
- name: Install Nginx
  apt: name={{ item }} state=present update_cache=yes
  with_items:
     - nginx
     - apache2-utils

- name: Remove the default file in nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Configure Nginx virtual host
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/nginx.conf
    owner: root
    group: root
  
    notify:
      - Restart Nginx
~                    
